services:
  db:
    container_name: db
    image: mongo
    restart: always
  db_admin:
    container_name: db_admin
    image: mongo-express
    ports:
      - 4001:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
    depends_on:
      - db