services:
  db:
    container_name: db
    image: mongo
    restart: always
  db_admin:
    container_name: db_admin
    image: mongo-express
    ports:
      - 4001:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_BASICAUTH_USERNAME=Gecko2654
      - ME_CONFIG_BASICAUTH_PASSWORD=d4MeToiPz4DLTLRLeEfefQ827G5QM3xbom7BhiWv
    depends_on:
      - db
  app:
    container_name: app
    build: .
    ports:
      - 4000:4000
    restart: always
    environment:
      - NODE_ENV=production